/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productId 
 * @param deviceId 
 * @param endpointUrl 
 * @param testId 
 */


data class PostTestClient200Response (

    @Json(name = "productId")
    val productId: kotlin.String,

    @Json(name = "deviceId")
    val deviceId: kotlin.String,

    @Json(name = "endpointUrl")
    val endpointUrl: kotlin.String,

    @Json(name = "testId")
    val testId: kotlin.String

) {


}

