/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param failHttp 
 * @param failWs 
 * @param endpointUrl 
 * @param extraClientConnectResponseData 
 */


data class PostTestClientRequest (

    @Json(name = "failHttp")
    val failHttp: kotlin.Boolean? = null,

    @Json(name = "failWs")
    val failWs: kotlin.Boolean? = null,

    @Json(name = "endpointUrl")
    val endpointUrl: kotlin.String? = null,

    @Json(name = "extraClientConnectResponseData")
    val extraClientConnectResponseData: kotlin.Boolean? = null

) {


}

