/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param failHttp 
 * @param failWs 
 * @param extraDeviceConnectResponseData 
 */


data class PostTestDeviceRequest (

    @Json(name = "failHttp")
    val failHttp: kotlin.Boolean? = null,

    @Json(name = "failWs")
    val failWs: kotlin.Boolean? = null,

    @Json(name = "extraDeviceConnectResponseData")
    val extraDeviceConnectResponseData: kotlin.Boolean? = null

) {


}

