/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param failHttp 
 * @param failWs 
 * @param endpointUrl specify the endpoint url the server returns in the test create response and the websocket url. Format http://<ip>:<port>
 * @param extraClientConnectResponseData 
 * @param requireAccessToken Set to true to force the client to use an access token when connecting
 * @param productIdNotFound set to true to force the client api to return a PRODUCT_ID_NOT_FOUND error
 * @param deviceIdNotFound set to true to force the client api to return a DEVICE_ID_NOT_FOUND error
 */


data class PostTestClientRequest (

    @Json(name = "failHttp")
    val failHttp: kotlin.Boolean? = null,

    @Json(name = "failWs")
    val failWs: kotlin.Boolean? = null,

    /* specify the endpoint url the server returns in the test create response and the websocket url. Format http://<ip>:<port> */
    @Json(name = "endpointUrl")
    val endpointUrl: kotlin.String? = null,

    @Json(name = "extraClientConnectResponseData")
    val extraClientConnectResponseData: kotlin.Boolean? = null,

    /* Set to true to force the client to use an access token when connecting */
    @Json(name = "requireAccessToken")
    val requireAccessToken: kotlin.Boolean? = null,

    /* set to true to force the client api to return a PRODUCT_ID_NOT_FOUND error */
    @Json(name = "productIdNotFound")
    val productIdNotFound: kotlin.Boolean? = null,

    /* set to true to force the client api to return a DEVICE_ID_NOT_FOUND error */
    @Json(name = "deviceIdNotFound")
    val deviceIdNotFound: kotlin.Boolean? = null

) {


}

