/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Ice-Server
 *
 * @param urls 
 * @param username 
 * @param credential 
 */


data class PostV1IceServers200ResponseIceServersInner (

    @Json(name = "urls")
    val urls: kotlin.collections.List<kotlin.String>,

    @Json(name = "username")
    val username: kotlin.String? = null,

    @Json(name = "credential")
    val credential: kotlin.String? = null

) {


}

