/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PostV1IceServers200ResponseIceServersInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param iceServers 
 */


data class PostV1IceServers200Response (

    @Json(name = "iceServers")
    val iceServers: kotlin.collections.List<PostV1IceServers200ResponseIceServersInner>

) {


}

