/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param signalingUrl 
 * @param deviceOnline 
 * @param channelId 
 * @param extraFieldInTheResponse 
 */


data class PostV1ClientConnect200Response (

    @Json(name = "signalingUrl")
    val signalingUrl: kotlin.String,

    @Json(name = "deviceOnline")
    val deviceOnline: kotlin.Boolean,

    @Json(name = "channelId")
    val channelId: kotlin.String,

    @Json(name = "extra_field_in_the_response")
    val extraFieldInTheResponse: kotlin.String? = null

) {


}

